### ISSUE TITLE
hico & polar dataset test

### ISSUE THREAD

**Issue by Hobeom** [WalterMa/Human-Object-Relation-Network#2]
First of all, thank you very much for revealing the code. :+1: 

I didn't see the performance of hico in the paper.
I wonder what the performance figures are compared to other papers.

We then find traces of experiments on polar datasets in the code.
https://github.com/WalterMa/Human-Object-Relation-Network/blob/711b7896c72d7573fd3b19e90042729a90a42b66/scripts/detection/eval_faster_rcnn.py#L47
I wish you to provide the polar dataset code.

**Comment by WalterMa** [comment]
1. About HICO datasets comparison, refer to our exetending paper (draft) : [IEEE_MM_MaWentao_0830.pdf](https://github.com/WalterMa/Human-Object-Relation-Network/files/6805724/IEEE_MM_MaWentao_0830.pdf)
![image](https://user-images.githubusercontent.com/7560132/125386530-08c81d80-e3cf-11eb-9de3-a433c5119337.png)

2. Polar dataset is our previous released dataset in the https://ieeexplore.ieee.org/document/9010160
The dataset download link, please refer to http://dx.doi.org/10.17632/hvnsh7rwz7.1

**Comment by Hobeom** [comment]
Thank you for your detailed reply.
It helped me a lot. :smile: 
I will try to experiment with your code.
How about performance in polar datasets using this repository horn network?
